# Generated by Django 5.0.14 on 2025-10-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/'),
        ),
    ]
