# Generated by Django 5.0.14 on 2025-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='x_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
